import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopAppBar from '../components/TopAppBar';
import BottomAppBar from '../components/BottomAppBar';
import { APP_NAME } from '@/lib/config';
import { AuthProvider } from '@/context/AuthContext';
import { SocketProvider } from '@/context/SocketContext';
import { PostProvider } from '@/context/PostContext';
import { NotificationProvider } from '@/context/NotificationContext';
import { CartProvider } from '@/context/CartContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="manifest" href="/manifest.json"></link>
      </head> */}
      <body>    
        <AuthProvider>
          <SocketProvider> 
            <NotificationProvider>
              <PostProvider>
                <CartProvider>  
                  <TopAppBar /> 
                  <div className="pt-16 pb-20">                
                    {children}                  
                  </div> 
                  <BottomAppBar /> 
                </CartProvider>
              </PostProvider> 
            </NotificationProvider> 
          </SocketProvider> 
        </AuthProvider>    
      </body>
    </html>
  );
}